"use client"

import Link from 'next/link'
import { useState } from 'react'

const ROUNDS = ['16강', '8강', '4강', '결승']

const INITIAL_MATCHES = [
  { id: 1, teamA: '김민준/박서연', teamB: '류승현/남지현', court: '코트1', time: '10:00', status: '완료', score: '11-4, 11-6' },
  { id: 2, teamA: '정수현/강다은', teamB: '오세훈/강지원', court: '코트2', time: '10:00', status: '완료', score: '11-7, 11-9' },
  { id: 3, teamA: '한태양/임소희', teamB: '배성민/조유진', court: '코트3', time: '14:00', status: '진행중', score: '' },
  { id: 4, teamA: '신동혁/문채원', teamB: '이준호/최지수', court: '코트4', time: '14:00', status: '예정', score: '' },
]

const ALL_TEAMS = [
  '김민준/박서연', '류승현/남지현', '정수현/강다은', '오세훈/강지원',
  '한태양/임소희', '배성민/조유진', '신동혁/문채원', '이준호/최지수',
]

const COURTS = ['코트1', '코트2', '코트3', '코트4']
const STATUSES = ['예정', '진행중', '완료']

const TEMPLATES = [
  {
    id: 'bracket',
    label: '대진표 공개 알림',
    preview: '[피클볼KR] 2025 서울 오픈 피클볼 챔피언십 대진표가 공개되었습니다. 지금 바로 확인하세요 👉 pickleball.kr/bracket',
  },
  {
    id: 'round',
    label: '8강 대진 배정 알림',
    preview: '[피클볼KR] 8강 대진이 배정되었습니다. 상대팀과 경기 시간을 확인해 주세요. 코트 배정은 당일 현장에서 안내됩니다.',
  },
  {
    id: 'schedule',
    label: '경기 일정 변경 알림',
    preview: '[피클볼KR] 일정이 변경되었습니다. 최신 대진표를 반드시 확인해 주세요. 문의: 010-0000-0000',
  },
]

const statusStyles: Record<string, string> = {
  '완료': 'bg-[#D1FAE5] text-[#065F46]',
  '진행중': 'bg-[#EDE9FE] text-[#5B21B6]',
  '예정': 'bg-[#F3F4F6] text-[#6B7280]',
}

type Match = typeof INITIAL_MATCHES[number]
type Notification = { date: string; title: string; count: number }
type SendStep = 'idle' | 'sending' | 'done'

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

function nowLabel() {
  const d = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}.${pad(d.getMonth() + 1)}.${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`
}

export default function BracketManagePage() {
  const [matches, setMatches] = useState<Match[]>(INITIAL_MATCHES)
  const [activeRound, setActiveRound] = useState(1)
  const [editMode, setEditMode] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [editForm, setEditForm] = useState<Partial<Match>>({})
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [toast, setToast] = useState<string | null>(null)

  // 알림톡 모달
  const [modalOpen, setModalOpen] = useState(false)
  const [selectedTemplate, setSelectedTemplate] = useState(TEMPLATES[0].id)
  const [sendStep, setSendStep] = useState<SendStep>('idle')
  const [notifications, setNotifications] = useState<Notification[]>([
    { date: '2025.06.28 08:00', title: '8강 대진 배정 알림', count: 98 },
    { date: '2025.06.27 18:00', title: '대진표 공개 알림', count: 98 },
  ])

  const showToast = (msg: string) => {
    setToast(msg)
    setTimeout(() => setToast(null), 2500)
  }

  const openModal = () => {
    setSelectedTemplate(TEMPLATES[0].id)
    setSendStep('idle')
    setModalOpen(true)
  }

  const closeModal = () => {
    if (sendStep === 'sending') return
    setModalOpen(false)
    setSendStep('idle')
  }

  const handleSend = () => {
    setSendStep('sending')
    setTimeout(() => {
      const tpl = TEMPLATES.find(t => t.id === selectedTemplate)!
      setNotifications(prev => [
        { date: nowLabel(), title: tpl.label, count: 98 },
        ...prev,
      ])
      setSendStep('done')
    }, 1800)
  }

  const handleModalClose = () => {
    closeModal()
    if (sendStep === 'done') showToast('알림톡이 98명에게 성공적으로 발송되었습니다. 💬')
  }

  const handleAutoGenerate = () => {
    const teams = shuffle(ALL_TEAMS)
    const generated: Match[] = []
    for (let i = 0; i < teams.length; i += 2) {
      const idx = i / 2
      generated.push({
        id: idx + 1,
        teamA: teams[i],
        teamB: teams[i + 1],
        court: COURTS[idx % COURTS.length],
        time: idx < 2 ? '10:00' : '14:00',
        status: '예정',
        score: '',
      })
    }
    setMatches(generated)
    setAutoGenerated(true)
    setEditMode(false)
    setEditingId(null)
    showToast('대진표가 자동 생성되었습니다.')
  }

  const startEdit = (match: Match) => {
    setEditingId(match.id)
    setEditForm({ ...match })
  }

  const cancelEdit = () => {
    setEditingId(null)
    setEditForm({})
  }

  const saveEdit = () => {
    setMatches(prev =>
      prev.map(m => m.id === editingId ? { ...m, ...editForm } as Match : m)
    )
    setEditingId(null)
    setEditForm({})
    showToast('수정 사항이 저장되었습니다.')
  }

  const toggleEditMode = () => {
    setEditMode(prev => !prev)
    setEditingId(null)
    setEditForm({})
  }

  const currentTemplate = TEMPLATES.find(t => t.id === selectedTemplate)!

  return (
    <div className="min-h-screen bg-[#F8F7FF]">
      {/* Toast */}
      {toast && (
        <div className="fixed top-4 left-1/2 -translate-x-1/2 z-50 px-5 py-3 bg-[#1F2937] text-white text-sm font-semibold rounded-xl shadow-xl">
          {toast}
        </div>
      )}

      {/* 알림톡 발송 모달 */}
      {modalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* backdrop */}
          <div
            className="absolute inset-0 bg-black/40 backdrop-blur-sm"
            onClick={handleModalClose}
          />
          <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 space-y-5">
            {sendStep === 'done' ? (
              /* ── 발송 완료 화면 ── */
              <div className="flex flex-col items-center py-6 gap-4 text-center">
                <div className="w-16 h-16 rounded-full bg-[#D1FAE5] flex items-center justify-center text-3xl">
                  ✅
                </div>
                <div>
                  <p className="text-lg font-bold text-[#1F2937]">발송 완료!</p>
                  <p className="text-sm text-[#6B7280] mt-1">
                    <span className="font-semibold text-[#10B981]">98명</span>의 참가자에게<br />
                    알림톡이 성공적으로 발송되었습니다.
                  </p>
                </div>
                <button
                  onClick={handleModalClose}
                  className="w-full py-3 bg-[#10B981] text-white font-bold rounded-xl hover:bg-[#059669] transition-colors"
                >
                  확인
                </button>
              </div>
            ) : (
              /* ── 발송 설정 화면 ── */
              <>
                <div className="flex items-center justify-between">
                  <h3 className="text-base font-bold text-[#1F2937]">알림톡 발송</h3>
                  <button
                    onClick={handleModalClose}
                    className="text-[#9CA3AF] hover:text-[#1F2937] text-xl leading-none"
                  >
                    ✕
                  </button>
                </div>

                {/* 수신자 */}
                <div className="flex items-center gap-3 bg-[#F8F7FF] rounded-xl p-3 border border-[#E5E7EB]">
                  <span className="text-lg">👥</span>
                  <div>
                    <p className="text-xs text-[#6B7280] font-semibold">수신 대상</p>
                    <p className="text-sm font-bold text-[#1F2937]">전체 참가자 98명</p>
                  </div>
                </div>

                {/* 템플릿 선택 */}
                <div className="space-y-2">
                  <p className="text-xs font-bold text-[#6B7280] uppercase tracking-wide">메시지 템플릿</p>
                  {TEMPLATES.map(tpl => (
                    <label
                      key={tpl.id}
                      className={`flex items-start gap-3 p-3 rounded-xl border cursor-pointer transition-colors ${
                        selectedTemplate === tpl.id
                          ? 'border-[#6D28D9] bg-[#EDE9FE]'
                          : 'border-[#E5E7EB] hover:bg-[#F8F7FF]'
                      }`}
                    >
                      <input
                        type="radio"
                        name="template"
                        value={tpl.id}
                        checked={selectedTemplate === tpl.id}
                        onChange={() => setSelectedTemplate(tpl.id)}
                        className="mt-0.5 accent-[#6D28D9]"
                      />
                      <span className={`text-sm font-semibold ${selectedTemplate === tpl.id ? 'text-[#6D28D9]' : 'text-[#1F2937]'}`}>
                        {tpl.label}
                      </span>
                    </label>
                  ))}
                </div>

                {/* 미리보기 */}
                <div className="bg-[#F8F7FF] rounded-xl border border-[#E5E7EB] p-4 space-y-1">
                  <p className="text-xs font-bold text-[#6B7280] uppercase tracking-wide">미리보기</p>
                  <p className="text-sm text-[#1F2937] leading-relaxed">{currentTemplate.preview}</p>
                </div>

                {/* 발송 버튼 */}
                <button
                  onClick={handleSend}
                  disabled={sendStep === 'sending'}
                  className="w-full py-3 bg-[#10B981] text-white font-bold rounded-xl hover:bg-[#059669] disabled:opacity-70 transition-all flex items-center justify-center gap-2"
                >
                  {sendStep === 'sending' ? (
                    <>
                      <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="white" strokeWidth="4" />
                        <path className="opacity-75" fill="white" d="M4 12a8 8 0 018-8v4l3-3-3-3v4a8 8 0 00-8 8h4z" />
                      </svg>
                      발송 중…
                    </>
                  ) : (
                    <>💬 98명에게 발송하기</>
                  )}
                </button>
              </>
            )}
          </div>
        </div>
      )}

      {/* Page header */}
      <div className="bg-white border-b border-[#E5E7EB]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <Link
            href="/host/tournaments"
            className="text-sm text-[#6B7280] hover:text-[#6D28D9] transition-colors font-semibold inline-flex items-center gap-1 mb-3"
          >
            ← 대회 관리
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-[#1F2937]">대진표 관리</h1>
            <p className="text-[#6B7280] mt-0.5 text-sm">2025 서울 오픈 피클볼 챔피언십</p>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
        {/* Status banner */}
        <div className="bg-[#D1FAE5] border border-[#6EE7B7] rounded-xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <span className="text-lg">✅</span>
            <p className="text-sm font-semibold text-[#065F46]">
              {autoGenerated
                ? '대진표가 자동 생성되었습니다. 참가자들에게 알림톡을 발송해 주세요.'
                : '대진표가 공개되었습니다. 참가자들이 대진표를 확인할 수 있습니다.'}
            </p>
          </div>
          <button className="shrink-0 px-4 py-2 text-sm font-semibold border border-[#6EE7B7] text-[#065F46] rounded-lg hover:bg-[#A7F3D0] transition-colors bg-white">
            대진표 숨기기
          </button>
        </div>

        {/* Action buttons */}
        <div className="flex flex-wrap gap-3">
          <button
            onClick={handleAutoGenerate}
            className="px-5 py-2.5 bg-[#6D28D9] text-white font-bold rounded-xl hover:bg-[#5B21B6] active:scale-95 transition-all text-sm flex items-center gap-2"
          >
            <span>⚡</span> 대진표 자동 생성
          </button>
          <button
            onClick={toggleEditMode}
            className={`px-5 py-2.5 font-semibold rounded-xl transition-all text-sm border ${
              editMode
                ? 'bg-[#EDE9FE] border-[#6D28D9] text-[#6D28D9]'
                : 'border-[#E5E7EB] text-[#1F2937] hover:bg-[#F8F7FF]'
            }`}
          >
            {editMode ? '✏️ 수정 모드 ON — 클릭해서 끄기' : '수동 수정 모드'}
          </button>
          <button
            onClick={openModal}
            className="px-5 py-2.5 bg-[#10B981] text-white font-bold rounded-xl hover:bg-[#059669] active:scale-95 transition-all text-sm flex items-center gap-2"
          >
            <span>💬</span> 참가자에게 알림톡 발송
          </button>
        </div>

        {/* Round selector */}
        <div className="flex gap-1 bg-white rounded-xl border border-[#E5E7EB] p-1 w-fit shadow-sm">
          {ROUNDS.map((round, i) => (
            <button
              key={round}
              onClick={() => setActiveRound(i)}
              className={`px-5 py-2 rounded-lg text-sm font-semibold transition-colors ${
                activeRound === i
                  ? 'bg-[#6D28D9] text-white shadow-sm'
                  : 'text-[#6B7280] hover:text-[#1F2937]'
              }`}
            >
              {round}
            </button>
          ))}
        </div>

        {/* Bracket */}
        <div className="bg-white rounded-2xl border border-[#E5E7EB] shadow-sm p-6">
          <div className="flex items-center justify-between mb-5">
            <h2 className="font-bold text-[#1F2937]">{ROUNDS[activeRound]} 대진표</h2>
            {editMode && (
              <span className="text-xs font-semibold text-[#6D28D9] bg-[#EDE9FE] px-3 py-1 rounded-full">
                수정 모드 활성화
              </span>
            )}
          </div>

          <div className="space-y-3">
            {matches.map((match) =>
              editingId === match.id ? (
                <div
                  key={match.id}
                  className="p-4 border-2 border-[#6D28D9] rounded-xl bg-[#F5F3FF] space-y-3"
                >
                  <p className="text-xs font-bold text-[#6D28D9] mb-1">Match {match.id} 수정</p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs text-[#6B7280] font-semibold block mb-1">팀 A</label>
                      <input
                        className="w-full border border-[#E5E7EB] rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-[#6D28D9]"
                        value={editForm.teamA ?? ''}
                        onChange={e => setEditForm(f => ({ ...f, teamA: e.target.value }))}
                      />
                    </div>
                    <div>
                      <label className="text-xs text-[#6B7280] font-semibold block mb-1">팀 B</label>
                      <input
                        className="w-full border border-[#E5E7EB] rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-[#6D28D9]"
                        value={editForm.teamB ?? ''}
                        onChange={e => setEditForm(f => ({ ...f, teamB: e.target.value }))}
                      />
                    </div>
                    <div>
                      <label className="text-xs text-[#6B7280] font-semibold block mb-1">코트</label>
                      <select
                        className="w-full border border-[#E5E7EB] rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-[#6D28D9] bg-white"
                        value={editForm.court ?? ''}
                        onChange={e => setEditForm(f => ({ ...f, court: e.target.value }))}
                      >
                        {COURTS.map(c => <option key={c}>{c}</option>)}
                      </select>
                    </div>
                    <div>
                      <label className="text-xs text-[#6B7280] font-semibold block mb-1">시간</label>
                      <input
                        type="time"
                        className="w-full border border-[#E5E7EB] rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-[#6D28D9]"
                        value={editForm.time ?? ''}
                        onChange={e => setEditForm(f => ({ ...f, time: e.target.value }))}
                      />
                    </div>
                    <div>
                      <label className="text-xs text-[#6B7280] font-semibold block mb-1">상태</label>
                      <select
                        className="w-full border border-[#E5E7EB] rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-[#6D28D9] bg-white"
                        value={editForm.status ?? ''}
                        onChange={e => setEditForm(f => ({ ...f, status: e.target.value }))}
                      >
                        {STATUSES.map(s => <option key={s}>{s}</option>)}
                      </select>
                    </div>
                    <div>
                      <label className="text-xs text-[#6B7280] font-semibold block mb-1">스코어</label>
                      <input
                        className="w-full border border-[#E5E7EB] rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-[#6D28D9]"
                        placeholder="예: 11-4, 11-6"
                        value={editForm.score ?? ''}
                        onChange={e => setEditForm(f => ({ ...f, score: e.target.value }))}
                      />
                    </div>
                  </div>
                  <div className="flex gap-2 pt-1">
                    <button
                      onClick={saveEdit}
                      className="px-4 py-2 bg-[#6D28D9] text-white text-sm font-bold rounded-lg hover:bg-[#5B21B6] transition-colors"
                    >
                      저장
                    </button>
                    <button
                      onClick={cancelEdit}
                      className="px-4 py-2 border border-[#E5E7EB] text-[#6B7280] text-sm font-semibold rounded-lg hover:bg-[#F3F4F6] transition-colors"
                    >
                      취소
                    </button>
                  </div>
                </div>
              ) : (
                <div
                  key={match.id}
                  className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-4 border border-[#E5E7EB] rounded-xl hover:bg-[#F8F7FF] transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-bold text-[#6B7280] w-14 shrink-0">
                      Match {match.id}
                    </span>
                    <div className="flex items-center gap-2 text-sm font-semibold text-[#1F2937]">
                      <span>{match.teamA}</span>
                      <span className="text-[#9CA3AF] font-normal text-xs">vs</span>
                      <span>{match.teamB}</span>
                    </div>
                  </div>
                  <div className="flex flex-wrap items-center gap-3 shrink-0">
                    <span className="text-xs text-[#6B7280]">{match.court}</span>
                    <span className="text-xs text-[#6B7280]">{match.time}</span>
                    {match.score && (
                      <span className="text-xs font-semibold text-[#6D28D9]">{match.score}</span>
                    )}
                    <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${statusStyles[match.status]}`}>
                      {match.status}
                    </span>
                    {editMode && (
                      <button
                        onClick={() => startEdit(match)}
                        className="px-3 py-1.5 text-xs font-semibold border border-[#E5E7EB] rounded-lg text-[#1F2937] hover:bg-[#EDE9FE] hover:border-[#6D28D9] hover:text-[#6D28D9] transition-colors"
                      >
                        수정
                      </button>
                    )}
                  </div>
                </div>
              )
            )}
          </div>

          <p className="mt-4 text-xs text-[#9CA3AF] bg-[#F8F7FF] rounded-lg p-3">
            {editMode
              ? '각 경기 행의 [수정] 버튼을 눌러 대진 순서, 코트, 시간, 스코어를 변경하세요.'
              : '수동 수정 모드를 활성화하면 각 경기를 개별 수정할 수 있습니다.'}
          </p>
        </div>

        {/* 알림톡 발송 내역 */}
        <div className="bg-white rounded-2xl border border-[#E5E7EB] shadow-sm p-6">
          <div className="flex items-center justify-between mb-5">
            <h2 className="font-bold text-[#1F2937]">알림톡 발송 내역</h2>
            <button
              onClick={openModal}
              className="px-4 py-2 bg-[#10B981] text-white font-semibold rounded-xl hover:bg-[#059669] active:scale-95 transition-all text-sm"
            >
              새 알림톡 발송
            </button>
          </div>
          {notifications.length === 0 ? (
            <p className="text-sm text-[#9CA3AF] text-center py-8">발송 내역이 없습니다.</p>
          ) : (
            <div className="space-y-3">
              {notifications.map((n, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between p-4 bg-[#F8F7FF] rounded-xl border border-[#E5E7EB]"
                >
                  <div>
                    <p className="text-sm font-semibold text-[#1F2937]">{n.title}</p>
                    <p className="text-xs text-[#6B7280] mt-0.5">{n.date}</p>
                  </div>
                  <span className="text-xs font-semibold text-[#10B981] bg-[#D1FAE5] px-2.5 py-1 rounded-full">
                    {n.count}명 발송 완료
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
